-- Enable pgcrypto for gen_random_uuid()
create extension if not exists pgcrypto;

-- 1. PROFILES TABLE
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  full_name text,
  avatar_url text,
  subscription_status text default 'free' check (subscription_status in ('free', 'pro')) not null,
  theme text default 'system' check (theme in ('light', 'dark', 'system')) not null,
  dropbox_refresh_token text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on profiles
alter table public.profiles enable row level security;

-- Profiles Policies
create policy "Users can view their own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Trigger to automatically insert profile on auth.users sign-up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. COLLECTIONS TABLE
create table public.collections (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  parent_id bigint references public.collections(id) on delete cascade,
  title text not null,
  icon text,
  color text,
  is_public boolean default false not null,
  sort_order integer default 0 not null,
  view_mode text default 'list' check (view_mode in ('grid', 'list', 'masonry', 'headlines')) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on collections
alter table public.collections enable row level security;

-- Collections Policies
create policy "Users can view public collections or their own"
  on public.collections for select
  using (auth.uid() = user_id or is_public = true);

create policy "Users can insert their own collections"
  on public.collections for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own collections"
  on public.collections for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own collections"
  on public.collections for delete
  using (auth.uid() = user_id);


-- 3. BOOKMARKS TABLE
create table public.bookmarks (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  url text not null,
  title text not null,
  excerpt text,
  cover_url text,
  type text default 'link' check (type in ('link', 'article', 'video', 'image', 'document')) not null,
  collection_id bigint references public.collections(id) on delete set null,
  tags text[] default '{}'::text[] not null,
  reminder_at timestamp with time zone,
  is_broken boolean default false not null,
  domain text not null,
  dropbox_path text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on bookmarks
alter table public.bookmarks enable row level security;

-- Bookmarks Policies
create policy "Users can view bookmarks if they own them or the collection is public"
  on public.bookmarks for select
  using (
    auth.uid() = user_id 
    or collection_id in (select id from public.collections where is_public = true)
  );

create policy "Users can insert their own bookmarks"
  on public.bookmarks for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own bookmarks"
  on public.bookmarks for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own bookmarks"
  on public.bookmarks for delete
  using (auth.uid() = user_id);


-- 4. HIGHLIGHTS TABLE
create table public.highlights (
  id uuid default gen_random_uuid() primary key,
  bookmark_id uuid references public.bookmarks(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  text text not null,
  note text,
  color text default 'yellow' check (color in ('yellow', 'blue', 'red', 'green')) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on highlights
alter table public.highlights enable row level security;

-- Highlights Policies
create policy "Users can view highlights if they own them or if the bookmark is in a public collection"
  on public.highlights for select
  using (
    auth.uid() = user_id
    or bookmark_id in (
      select b.id from public.bookmarks b
      join public.collections c on b.collection_id = c.id
      where c.is_public = true
    )
  );

create policy "Users can insert their own highlights"
  on public.highlights for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own highlights"
  on public.highlights for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own highlights"
  on public.highlights for delete
  using (auth.uid() = user_id);


-- 5. TAGS TABLE
create table public.tags (
  user_id uuid references public.profiles(id) on delete cascade not null,
  name text not null,
  bookmark_count integer default 0 not null,
  primary key (user_id, name)
);

-- Enable RLS on tags
alter table public.tags enable row level security;

-- Tags Policies
create policy "Users can view their own tags"
  on public.tags for select
  using (auth.uid() = user_id);

create policy "Users can insert their own tags"
  on public.tags for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own tags"
  on public.tags for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own tags"
  on public.tags for delete
  using (auth.uid() = user_id);


-- 6. TIMESTAMPS AUTO-UPDATE TRIGGERS
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_profiles_updated_at
  before update on public.profiles
  for each row execute procedure public.handle_updated_at();

create trigger update_collections_updated_at
  before update on public.collections
  for each row execute procedure public.handle_updated_at();

create trigger update_bookmarks_updated_at
  before update on public.bookmarks
  for each row execute procedure public.handle_updated_at();
